# Generated by Django 3.2 on 2024-03-17 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="code",
            field = models.UUIDField()
        )
    ]
