# Generated by Django 3.2 on 2024-04-06 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='rooms',
            field=models.CharField(blank=True, help_text='Comma-separated list of room names', max_length=255),
        ),
    ]
