# Generated by Django 3.2 on 2024-04-09 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_room_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='adminRoom',
            field=models.JSONField(default=dict),
        ),
    ]
